"""T-44: build the lever (a) runtime and its negative control from the SHIPPING runtime.

Never hand-edited: every change below is a named, asserted substitution on
runtime/runtime.sql. So `diff runtime/runtime.sql spikes/T-44/runtime-par.sql` is exactly
the list in FINDINGS, and a change to the shipping file that moves an anchor fails loudly
here instead of producing a silently different variant.

  runtime-par.sql  LEVER (a). Genuinely parallel safe, with honest labels:
    1. xpr.num's overflow check rewritten WITHOUT an EXCEPTION block (see NUM_NEW).
    2. xpr.ecma_num pins `SET extra_float_digits = 1`. It was IMMUTABLE while reading float8's
       text output, which follows that session setting (KNOWN_DIVERGENCES
       "extra_float_digits_guc"). Pinning makes the label true. It is T-9's xpr.j fix,
       applied to the one other function that reads the setting.
    3. Every function labelled PARALLEL SAFE, after reading its body and the pg_proc entry of
       every builtin it calls.
  runtime-nc.sql   THE NEGATIVE CONTROL for K4. The shipping bodies UNCHANGED, every function
    labelled PARALLEL SAFE, so xpr.num keeps its EXCEPTION block. Under
    debug_parallel_query = on, a string coercion must raise. If it does not, the forced
    battery is not actually reaching a worker, and K4 is void.

Usage: python3 make_runtimes.py   (writes both files next to this one)
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "runtime", "runtime.sql")

NUM_OLD = """    BEGIN
      n := t::numeric;
    EXCEPTION WHEN numeric_value_out_of_range THEN
      IF t ~ '[eE]-' THEN
        RETURN t::float8;   -- tiny beyond numeric: float8's own native raise surfaces
      END IF;
      RAISE EXCEPTION 'xpr.num refusal: numeric string magnitude exceeds float8 range (DBL_MAX)'
        USING ERRCODE = 'XPR01',
              DETAIL  = 'value (truncated): ' || left(t, 40),
              HINT    = 'named refusal -- fall back to the Python evaluator and report which path ran';
    END;
"""

NUM_NEW = """    -- T-44 LEVER (a): the same check WITHOUT an EXCEPTION block.  A block with a handler
    -- opens a subtransaction, which PostgreSQL 16 refuses in parallel mode ("cannot start
    -- subtransactions during a parallel operation") -- so the block made this function,
    -- and every query that calls it, parallel UNSAFE.  pg_input_is_valid (PG16, parallel
    -- safe) asks numeric_in the same question as a soft error.  For a string that passed
    -- the regex above, numeric_in can fail only on range, so "not valid" here is exactly
    -- the numeric_value_out_of_range the handler used to catch.  Below 1001 characters
    -- with an exponent of at most 3 digits numeric cannot overflow (dscale <= 1999 against
    -- a limit of 16383; weight <= 1999 decimal digits against 131072), so the common path
    -- skips the second parse.  Equivalence is MEASURED, not argued: spikes/T-44/num_diff.py.
    IF (length(t) > 1000 OR t ~ '[eE][+-]?[0-9]{4}') AND NOT pg_input_is_valid(t, 'numeric') THEN
      IF t ~ '[eE]-' THEN
        RETURN t::float8;   -- tiny beyond numeric: float8's own native raise surfaces
      END IF;
      RAISE EXCEPTION 'xpr.num refusal: numeric string magnitude exceeds float8 range (DBL_MAX)'
        USING ERRCODE = 'XPR01',
              DETAIL  = 'value (truncated): ' || left(t, 40),
              HINT    = 'named refusal -- fall back to the Python evaluator and report which path ran';
    END IF;
    n := t::numeric;
"""

ECMA_OLD = """CREATE OR REPLACE FUNCTION xpr.ecma_num(x float8) RETURNS text
LANGUAGE plpgsql IMMUTABLE AS $$"""
ECMA_NEW = """CREATE OR REPLACE FUNCTION xpr.ecma_num(x float8) RETURNS text
LANGUAGE plpgsql IMMUTABLE
SET extra_float_digits = 1   -- T-44: the label was false; this makes it true (see header)
AS $$"""

HEADER = re.compile(r"^(LANGUAGE (?:sql|plpgsql) (?:IMMUTABLE|STABLE))", re.M)
N_FUNCTIONS = 23


def label_all(sql: str) -> str:
    out, n = HEADER.subn(r"\1 PARALLEL SAFE", sql)
    assert n == N_FUNCTIONS, f"expected {N_FUNCTIONS} function headers, labelled {n}"
    assert sql.count("CREATE OR REPLACE FUNCTION") == N_FUNCTIONS
    return out


def main() -> None:
    base = open(SRC, encoding="utf-8").read()
    assert base.count(NUM_OLD) == 1, "xpr.num's EXCEPTION block moved -- re-anchor NUM_OLD"
    assert base.count(ECMA_OLD) == 1, "xpr.ecma_num's header moved -- re-anchor ECMA_OLD"
    assert base.count("EXCEPTION WHEN") == 1, "a second EXCEPTION block appeared -- audit it"

    par = base.replace(NUM_OLD, NUM_NEW).replace(ECMA_OLD, ECMA_NEW)
    assert "EXCEPTION WHEN" not in par
    par = label_all(par)
    nc = label_all(base)

    banner = ("-- T-44 GENERATED by spikes/T-44/make_runtimes.py from runtime/runtime.sql -- DO NOT EDIT.\n"
              "-- {what}\n")
    with open(os.path.join(HERE, "runtime-par.sql"), "w", encoding="utf-8") as fh:
        fh.write(banner.format(what="LEVER (a): parallel safe, honest labels, xpr.num without an EXCEPTION block."))
        fh.write(par)
    with open(os.path.join(HERE, "runtime-nc.sql"), "w", encoding="utf-8") as fh:
        fh.write(banner.format(what="NEGATIVE CONTROL for K4: shipping bodies, every function labelled PARALLEL SAFE. Never ship this."))
        fh.write(nc)
    print("wrote runtime-par.sql and runtime-nc.sql")


if __name__ == "__main__":
    main()
