# T-1 · Conformance — expr(Python) vs compiled SQL(Postgres), per case

Generated by `spikes/T-1/proto/conformance.py` · PostgreSQL 16.14 (Debian 16.14-1.pgdg12+1) · db `autosql_spike` · Python 3.12.3
Fixture: `/home/corgea/Desktop/Coding Projects/GIMS-Project/tests/fixtures/expr_vectors.json` sha256 `0091df64283d91cb…` · `expr.py` sha256 `90cbb56d04b08b82…` · `compile.py` sha256 `b71b153802d0df94…` · `runtime.sql` sha256 `32628b45f2d1dd04…`

## The comparison rule (the oracle)

Mirrored **unchanged** from the existing consumer test, `GIMS-Project/tests/test_dashboard_expr.py:20-25`:

```python
def _matches(actual, expected) -> bool:
    if isinstance(expected, bool) or isinstance(actual, bool):
        return actual is expected or actual == expected and type(actual) is type(expected)
    if isinstance(expected, (int, float)) and isinstance(actual, (int, float)):
        return math.isclose(float(actual), float(expected), rel_tol=0, abs_tol=_EPS)
    return actual == expected
```

- **`float_epsilon` = 1e-09, applied ABSOLUTELY**, not relatively. That is not a choice made here: `test_dashboard_expr.py:24` passes `rel_tol=0, abs_tol=_EPS`, which disables the relative term. The fixture's own note says only "Numbers compare within 1e-9" and does not name a mode, so the existing test is the tiebreaker — and using it keeps this third runtime held to exactly the bar the Python and JS runtimes already pass.
- **Booleans never compare equal to 0/1.** The bool branch is first and requires `type(actual) is type(expected)`. `test_dashboard_expr.py:37-41` asserts this property of the language directly.
- **SQL NULL and jsonb `null` are kept apart.** The driver is never allowed to decode the value; Postgres is asked `v IS NULL`, `jsonb_typeof(v)` and `v::text` separately. A top-level jsonb `null` is a leak of `compile.py`'s representation contract (`compile.py:20-30`) and is scored **COMPILED_DIVERGES even if the decoded values look equal**.
- **Numeric normalization, stated once:** the SQL value is `json.loads(v::text)` with stdlib defaults — JSON integer literal → `int`, fractional/exponent literal → `float`, `Decimal` never appears, nothing re-typed afterwards. `to_jsonb(3.0::float8)::text` is the text `3`, so SQL legitimately yields `int 3` where Python yields `float 3.0`; the mirrored rule already treats those as the same number, which is exactly how the fixture's hand-authored `expect: 3` matches the evaluator's `3.0`.
- `extra_float_digits` pinned to `1` for the run (`KNOWN_DIVERGENCES/extra_float_digits_guc`).

## The four outcomes

- **`COMPILED_AGREES`** (PASS) — compile_ast() returned; the parameterised SQL executed; and matches(sql_value, python_value) is True under the rule mirrored from tests/test_dashboard_expr.py:20-25 (abs epsilon 1e-9, bools not equal to 0/1).
- **`COMPILED_DIVERGES`** (FAIL) — compile_ast() returned and the SQL executed, but matches() is False — OR the top-level value came back as jsonb 'null' instead of SQL NULL, which breaks compile.py's stated representation contract (compile.py:20-30) even when the decoded values happen to look equal. Cause is named per case.
- **`DID_NOT_COMPILE`** (GAP) — compile.py raised Uncompilable. No SQL was executed. This is an honest coverage gap and is NEVER counted as a pass.
- **`SQL_ERROR`** (RAISE) — Postgres RAISED while executing the compiled expression. expr is total (expr.py:640 'Never raises for data reasons'), so this is a TOTALITY VIOLATION — the most severe outcome in this spike. NEVER counted as a pass.

**`DID_NOT_COMPILE` and `SQL_ERROR` are not passes.** The pass rate below has the full case count as its denominator, and the harness asserts the four counts sum to it (`conformance.py`, `assert sum(counts.values()) == total`).

## Totals

| outcome | count | of |
| --- | ---: | ---: |
| `COMPILED_AGREES` | 130 | 130 |
| `COMPILED_DIVERGES` | 0 | 130 |
| `DID_NOT_COMPILE` | 0 | 130 |
| `SQL_ERROR` | 0 | 130 |

**Pass rate = 130/130 = 100.0%** — denominator is every fixture case, not every compiled case.

Agreement *among cases that compiled and executed* = 130/130. Quoted separately, and never as the headline.

## How strong is the agreement?

A pass count says nothing about how *closely* the two runtimes agree. Measured:

- **54 numeric cases. max |SQL − Python| = 0.0.** 0 case(s) needed the 1e-9 epsilon at all — the numeric agreement is **bit-exact**, not epsilon-assisted. The tolerance is present because the fixture defines it, but nothing in this run depends on it.
- **22/22 string cases are exact** character-for-character.
- **19 of 130 agreements are "both sides are null"** — a weaker form of agreement, quantified next.
- **6 cases call `today()`/`now()`, and 0 of them run on the real clock** — the fixture injects `context.now` for every one, which is what makes the run reproducible and what keeps `KNOWN_DIVERGENCES/wall_clock_granularity` out of scope here. Checked, not assumed. Two consecutive runs produce byte-identical `cases` in `results.json`.

### Degenerate baselines — what the fixture cannot distinguish

If an obviously wrong compiler still scores well here, that score is not evidence. Each row is a compiler that ignores its input entirely and emits one constant, scored under the identical comparison rule:

| degenerate compiler | would score | of |
| --- | ---: | ---: |
| `always 'true'::jsonb` | 20 | 130 |
| `always NULL::jsonb` | 19 | 130 |
| `always 'false'::jsonb` | 15 | 130 |
| `always to_jsonb(0::float8)` | 1 | 130 |
| `always to_jsonb(''::text)` | 0 | 130 |

The strongest do-nothing compiler scores **20/130 (15%)**. The real compiler scores 130/130, so **110 cases are agreement that no constant could have faked.**

## Is this harness capable of failing?

FRAMING.md §8: *"The conformance harness is the whole spike. If it is wrong, every finding downstream is wrong and looks green."* A clean sheet is worth nothing unless the harness demonstrably reports the other outcomes when it should. Each control feeds it a deliberately wrong input. They run **before** the conformance pass; if any fails the harness refuses to produce a report at all (`conformance.py main()`, exit 2).

| control | expected | got | ok |
| --- | --- | --- | :-: |
| NC1 unknown AST tag -> Uncompilable | `'Uncompilable'` | `'Uncompilable'` | yes |
| NC2 matches(999.0, 3.0) is False | `False` | `False` | yes |
| NC3a matches(3.0 + 1e-10, 3.0) is True | `True` | `True` | yes |
| NC3b matches(3.0 + 1e-8, 3.0) is False | `False` | `False` | yes |
| NC3c ABSOLUTE: matches(1e9 + 1.0, 1e9) is False | `False` | `False` | yes |
| NC4a matches(True, 1) is False | `False` | `False` | yes |
| NC4b matches(1, True) is False | `False` | `False` | yes |
| NC4c matches(True, True) is True | `True` | `True` | yes |
| NC4d matches(False, 0.0) is False | `False` | `False` | yes |
| NC5a matches(None, None) is True | `True` | `True` | yes |
| NC5b matches(None, 0.0) is False | `False` | `False` | yes |
| NC5c matches(0.0, None) is False | `False` | `False` | yes |
| NC6a mirrored rule passes [True] vs [1] | `True` | `True` | yes |
| NC6b strict check rejects [True] vs [1] | `False` | `False` | yes |
| NC7 division_by_zero -> SqlRaised | `'SqlRaised'` | `'SqlRaised'` | yes |
| NC8a NULL::jsonb -> is_sql_null True, jsonb_typeof None | `(True, None)` | `(True, None)` | yes |
| NC8b 'null'::jsonb -> is_sql_null False, jsonb_typeof 'null' | `(False, 'null')` | `(False, 'null')` | yes |
| NC9 data column is live (record 1 vs 2) | `('1', '2')` | `('1', '2')` | yes |
| NC10 ctx bind is live | `'"2030-01-15"'` | `'"2030-01-15"'` | yes |
| NC11 wrong SQL for fixture case 'add' is caught | `False` | `False` | yes |
| NC12 SQL NULL where Python has a value is caught | `False` | `False` | yes |
| NC13 a number where Python has null is caught (FRAMING §5) | `False` | `False` | yes |
| NC14 stray % refused | `'AssertionError'` | `'AssertionError'` | yes |

**23/23 controls pass.** In particular NC13 is FRAMING.md §5 stated as a test: a compiler output that turns a `null` into a number is caught, not scored as agreement.

## Mutation probe — is the record actually reaching Postgres?

For every compiled case the SAME compiled SQL is executed a second time against an **empty record** (context unchanged). A case that reads a field and returns the same answer either way never sent that field to the database.

- 68 of 130 cases read a field (`$` in the expression).
- 44 of those changed their answer on an empty record.
- 24 did not — listed below with why.

Of the 24 that did not change, 10 have a record that is ALREADY `{}` — for those the probe is a literal no-op and carries no information either way. The remaining 14 have a non-empty record and are genuinely invariant:

| case | expr | record | with record | with `{}` | why invariant |
| --- | --- | --- | --- | --- | --- |
| `descend_into_nondict_is_null` | `$.a.b` | `{"a": 5}` | `SQL NULL` | `SQL NULL` | $.a.b is null whether a is 5 or absent (expr.py:566-569) |
| `bracket_index_out_of_range_is_null` | `$.arr[5]` | `{"arr": [1]}` | `SQL NULL` | `SQL NULL` | index 5 is out of range for [1] and for absent |
| `add_missing_field` | `$.a + $.b` | `{"a": 2}` | `SQL NULL` | `SQL NULL` | $.b is absent in BOTH records, so the sum is null either way |
| `mul_nonnumeric_string` | `$.a * 2` | `{"a": "abc"}` | `SQL NULL` | `SQL NULL` | _to_num('abc') is None, same as _to_num(absent) |
| `eq_string_false` | `$.s == "FAIL"` | `{"s": "pass"}` | `false` | `false` | 'pass' != 'FAIL' and null != 'FAIL' — both false |
| `neq_string_true` | `$.s != "FAIL"` | `{"s": "pass"}` | `true` | `true` | 'pass' != 'FAIL' and null != 'FAIL' — both true |
| `order_mixed_types_is_null` | `$.n < "x"` | `{"n": 5}` | `SQL NULL` | `SQL NULL` | 5 < 'x' is null (mixed types); absent < 'x' is null too |
| `and_with_falsy_zero` | `$.a and $.b` | `{"a": 1, "b": 0}` | `false` | `false` | 0 is falsy and absent is falsy — both false |
| `empty_list_falsy` | `not $.list` | `{"list": []}` | `true` | `true` | [] is falsy and absent is falsy — both true under not |
| `contains_substring_false` | `contains($.s, "xyz")` | `{"s": "hello"}` | `false` | `false` | 'xyz' not in 'hello' and not in null — both false |
| `contains_list_member_false` | `contains($.tags, "z")` | `{"tags": ["a", "b"]}` | `false` | `false` | 'z' not in ['a','b'] and not in null — both false |
| `length_number_null` | `length($.n)` | `{"n": 5}` | `SQL NULL` | `SQL NULL` | length(5) is null (expr.py:543 non-str/list) as is length(abs… |
| `avg_empty_null` | `avg($.list)` | `{"list": []}` | `SQL NULL` | `SQL NULL` | avg([]) is null and avg(absent) is null |
| `if_false_branch` | `if($.n > 0, "pos", "neg")` | `{"n": -5}` | `"neg"` | `"neg"` | -5 > 0 is false and absent > 0 is null — both take the else b… |

The probe is a coarse liveness check, not the proof. **NC9 is the direct proof that `data` is live**: the same SQL over `{"k":1}` and `{"k":2}` returns `1` and `2`.

## SQL_ERROR — totality violations (most severe)

None. No compiled case caused Postgres to raise.

## DID_NOT_COMPILE — coverage gaps (not passes)

None. Every fixture case compiled.

## COMPILED_DIVERGES — with cause

None.

## Control — the Python evaluator against the fixture's hand-authored `expect`

The fixture note says the expected values are hand-authored and must **not** be regenerated from an evaluator, so this is a real check on the oracle, not a tautology.

**130/130 agree.** The Python evaluator satisfies every hand-authored `expect` under the same rule used above. The oracle is sound.

## strict-vs-mirrored

The mirrored rule only reaches inside a container through Python's own `==` (`test_dashboard_expr.py:25`), which conflates `True` with `1` and `1` with `1.0` at every nested level. A stricter type-aware deep comparison runs alongside it. The mirrored rule stays the verdict; disagreements are listed, never silently resolved.

No case passes under the mirrored rule while failing the stricter deep check.

## Out-of-fixture probes — NOT part of the 130

A clean sheet is a statement about the **fixture**, not about the compiler. Every entry in `compile.py`'s own `KNOWN_DIVERGENCES` is marked `in_fixture: False`, so the 130 cases cannot confirm or refute any of them. These probes do, and they are counted **separately** — they change none of the totals above. Per FRAMING.md §3 nothing found here was fixed.

| probe | expr | record | Python | SQL | verdict |
| --- | --- | --- | --- | --- | --- |
| `overflow_via_multiply` | `$.a * $.b` | `{'a': 1e+200, 'b': 1e…` | `inf` | `RAISED 22003: ERROR:  value out of range: ove…` | **SQL_ERROR (totality violation)** |
| `overflow_via_add` | `$.a + $.a` | `{'a': 1e+296}` | `2e+296` | `200000000000000000000000000000000000000000000…` | **agrees** |
| `f8_guard_1e300_arith` | `$.a + 0` | `{'a': 1e+300}` | `1e+300` | `SQL NULL` | **DIVERGES** |
| `f8_guard_1e297_arith` | `$.a * 1` | `{'a': 1e+297}` | `1e+297` | `SQL NULL` | **DIVERGES** |
| `f8_guard_1e290_arith` | `$.a + 0` | `{'a': 1e+290}` | `1e+290` | `100000000000000000000000000000000000000000000…` | **agrees** |
| `f8_readback_1e300_no_arith` | `$.a` | `{'a': 1e+300}` | `1e+300` | `100000000000000000000000000000000000000000000…` | **agrees** |
| `num_of_1e999_string` | `number($.s)` | `{'s': '1e999'}` | `inf` | `SQL NULL` | **DIVERGES** |
| `unicode_upper_sharp_s` | `upper($.s)` | `{'s': 'straße'}` | `'STRASSE'` | `"STRAßE"` | **DIVERGES** |

**Two defects are confirmed here, both outside the fixture's reach:**

1. **`float8_overflow_raises` is real and reachable.** `$.a * $.b` with `a = b = 1e200` returns `inf` in Python and **raises `22003 value out of range: overflow`** in Postgres. `expr` is total (`expr.py:640`); this aborts the query. It is the one KNOWN_DIVERGENCES entry marked `guarded: false` that is a genuine totality violation, and it now has a witness.
2. **A defect NOT in KNOWN_DIVERGENCES: the `xpr.f8` range guard is ~12 orders of magnitude too tight.** The literal in `runtime.sql` (the `abs(...) > 1797693...` comparison in `xpr.f8`, repeated in `xpr.num`) is **297 digits long where DBL_MAX needs 309**; it evaluates to `1.797693134862316e+296`, not `1.7976931348623157e+308` (verified: `select length('1797…000'), '1797…000'::float8` → `297`, `1.797693134862316e+296`). So any JSON number with `|v|` between ~`1.8e296` and `DBL_MAX` is silently turned into NULL the moment it passes through arithmetic or `number()`: `$.a + 0` with `a = 1e300` gives `1e+300` in Python and **SQL NULL**. A bare field read is unaffected, because it never calls `xpr.f8`. This is a silent value-to-null divergence — not the disqualifying direction under FRAMING.md §5 (null-to-number), but wrong and silent, and it is **not** recorded in `KNOWN_DIVERGENCES`. Left unfixed per the stop rules: if `runtime.sql` is wrong, that IS the finding.

The `unicode_case_and_collation` entry also gains a witness: `upper("straße")` is `STRASSE` in Python and `STRAßE` in Postgres. The `jsonb_numeric_is_not_ieee_double` entry could **not** be probed this way — a record built from Python floats has already collapsed to IEEE doubles before it reaches jsonb, so the probe would be vacuous. It stays unconfirmed, not refuted.


## Per case — all 130 cases, grouped by the fixture's own groups

FRAMING.md §4 finding #1 requires pass/fail **per case**, never a summary count. Every row is here.

### `arithmetic` — 11 cases (PASS 11)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `add` | `1 + 2` | **PASS** `COMPILED_AGREES` | `3.0` (float) | `3` (int, jsonb number) |  |
| 2 | `precedence_mul_before_add` | `10 - 4 * 2` | **PASS** `COMPILED_AGREES` | `2.0` (float) | `2` (int, jsonb number) |  |
| 3 | `parens_override` | `(10 - 4) * 2` | **PASS** `COMPILED_AGREES` | `12.0` (float) | `12` (int, jsonb number) |  |
| 4 | `true_division` | `7 / 2` | **PASS** `COMPILED_AGREES` | `3.5` (float) | `3.5` (float, jsonb number) |  |
| 5 | `modulo_pos` | `7 % 3` | **PASS** `COMPILED_AGREES` | `1.0` (float) | `1` (int, jsonb number) |  |
| 6 | `modulo_neg_dividend_truncates` | `-5 % 3` | **PASS** `COMPILED_AGREES` | `-2.0` (float) | `-2` (int, jsonb number) |  |
| 7 | `modulo_neg_divisor_truncates` | `5 % -3` | **PASS** `COMPILED_AGREES` | `2.0` (float) | `2` (int, jsonb number) |  |
| 8 | `unary_minus` | `-3 + 1` | **PASS** `COMPILED_AGREES` | `-2.0` (float) | `-2` (int, jsonb number) |  |
| 9 | `mul_unary` | `2 * -3` | **PASS** `COMPILED_AGREES` | `-6.0` (float) | `-6` (int, jsonb number) |  |
| 10 | `divide_by_zero_is_null` | `5 / 0` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 11 | `modulo_by_zero_is_null` | `5 % 0` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |

### `fields` — 9 cases (PASS 9)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `simple` | `$.a` | **PASS** `COMPILED_AGREES` | `5` (int) | `5` (int, jsonb number) |  |
| 2 | `nested` | `$.a.b` | **PASS** `COMPILED_AGREES` | `7` (int) | `7` (int, jsonb number) |  |
| 3 | `missing_top` | `$.missing` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 4 | `descend_into_nondict_is_null` | `$.a.b` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 5 | `bracket_quoted_key_with_space` | `$["weird key"]` | **PASS** `COMPILED_AGREES` | `9` (int) | `9` (int, jsonb number) |  |
| 6 | `bracket_index` | `$.list[1]` | **PASS** `COMPILED_AGREES` | `20` (int) | `20` (int, jsonb number) |  |
| 7 | `bracket_negative_index` | `$.list[-1]` | **PASS** `COMPILED_AGREES` | `30` (int) | `30` (int, jsonb number) |  |
| 8 | `bracket_index_out_of_range_is_null` | `$.arr[5]` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 9 | `deep_nested_key` | `$.results.ph` | **PASS** `COMPILED_AGREES` | `7.4` (float) | `7.4` (float, jsonb number) |  |

### `null_propagation` — 4 cases (PASS 4)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `add_missing_field` | `$.a + $.b` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 2 | `add_present_fields` | `$.a + $.b` | **PASS** `COMPILED_AGREES` | `5.0` (float) | `5` (int, jsonb number) |  |
| 3 | `mul_nonnumeric_string` | `$.a * 2` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 4 | `add_numeric_string_coerces` | `$.a + 1` | **PASS** `COMPILED_AGREES` | `6.0` (float) | `6` (int, jsonb number) |  |

### `comparison` — 17 cases (PASS 17)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `lt_true` | `$.n < 7` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 2 | `lt_false` | `$.n < 7` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 3 | `lt_missing_is_null` | `$.n < 7` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 4 | `eq_string_true` | `$.s == "FAIL"` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 5 | `eq_string_false` | `$.s == "FAIL"` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 6 | `neq_string_true` | `$.s != "FAIL"` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 7 | `eq_num_true` | `1 == 1` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 8 | `eq_num_false` | `1 == 2` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 9 | `null_eq_null` | `null == null` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 10 | `missing_eq_null_true` | `$.x == null` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 11 | `zero_eq_null_false` | `$.x == null` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 12 | `bool_eq_bool` | `true == true` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 13 | `bool_ne_num` | `true == 1` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 14 | `string_ne_num` | `"2" == 2` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 15 | `string_lex_lt` | `"apple" < "banana"` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 16 | `gte_equal` | `$.n >= 10` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 17 | `order_mixed_types_is_null` | `$.n < "x"` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |

### `boolean` — 13 cases (PASS 13)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `and_ff` | `true and false` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 2 | `or_tf` | `true or false` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 3 | `not_true` | `not true` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 4 | `not_missing_is_true` | `not $.x` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 5 | `and_with_falsy_zero` | `$.a and $.b` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 6 | `or_with_truthy` | `$.a or $.b` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 7 | `not_of_comparison` | `not (1 < 2)` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 8 | `range_check` | `$.n > 0 and $.n < 10` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 9 | `empty_string_falsy` | `not ""` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 10 | `nonempty_string_truthy` | `not "x"` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 11 | `zero_falsy` | `not 0` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 12 | `empty_list_falsy` | `not $.list` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 13 | `nonempty_list_truthy` | `not $.list` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |

### `dates` — 13 cases (PASS 13)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `today_from_now` | `today()` | **PASS** `COMPILED_AGREES` | `'2026-07-02'` (str) | `'2026-07-02'` (str, jsonb string) |  |
| 2 | `now_from_now` | `now()` | **PASS** `COMPILED_AGREES` | `'2026-07-02T09:30:00Z'` (str) | `'2026-07-02T09:30:00Z'` (str, jsonb string) |  |
| 3 | `days_between_today_future` | `days_between(today(), $.due)` | **PASS** `COMPILED_AGREES` | `8.0` (float) | `8` (int, jsonb number) |  |
| 4 | `days_between_reverse_negative` | `days_between("2026-07-02", "2026-07-01")` | **PASS** `COMPILED_AGREES` | `-1.0` (float) | `-1` (int, jsonb number) |  |
| 5 | `days_between_two_days` | `days_between("2026-07-01", "2026-07-03")` | **PASS** `COMPILED_AGREES` | `2.0` (float) | `2` (int, jsonb number) |  |
| 6 | `days_between_fractional` | `days_between("2026-07-01T12:00:00Z", "2…` | **PASS** `COMPILED_AGREES` | `0.5` (float) | `0.5` (float, jsonb number) |  |
| 7 | `days_between_offset_aware` | `days_between("2026-07-01T00:00:00+02:00…` | **PASS** `COMPILED_AGREES` | `0.08333333333333333` (float) | `0.08333333333333333` (float, jsonb number) |  |
| 8 | `days_between_bad_input_null` | `days_between("bad", "2026-07-01")` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 9 | `date_add_days` | `date_add("2026-07-02", 7)` | **PASS** `COMPILED_AGREES` | `'2026-07-09'` (str) | `'2026-07-09'` (str, jsonb string) |  |
| 10 | `date_add_negative` | `date_add("2026-07-02", -2)` | **PASS** `COMPILED_AGREES` | `'2026-06-30'` (str) | `'2026-06-30'` (str, jsonb string) |  |
| 11 | `date_add_datetime_preserves_time` | `date_add("2026-07-02T10:00:00Z", 1)` | **PASS** `COMPILED_AGREES` | `'2026-07-03T10:00:00Z'` (str) | `'2026-07-03T10:00:00Z'` (str, jsonb string) |  |
| 12 | `date_add_year_rollover` | `date_add("2026-12-31", 1)` | **PASS** `COMPILED_AGREES` | `'2027-01-01'` (str) | `'2027-01-01'` (str, jsonb string) |  |
| 13 | `date_add_bad_input_null` | `date_add("nope", 1)` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |

### `coalesce` — 4 cases (PASS 4)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `second_non_null` | `coalesce($.a, $.b, 0)` | **PASS** `COMPILED_AGREES` | `5` (int) | `5` (int, jsonb number) |  |
| 2 | `all_missing_default` | `coalesce($.a, $.b, 0)` | **PASS** `COMPILED_AGREES` | `0.0` (float) | `0` (int, jsonb number) |  |
| 3 | `all_null_returns_null` | `coalesce($.a, $.b)` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 4 | `skip_literal_null` | `coalesce(null, 3)` | **PASS** `COMPILED_AGREES` | `3.0` (float) | `3` (int, jsonb number) |  |

### `strings` — 11 cases (PASS 11)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `lower` | `lower($.s)` | **PASS** `COMPILED_AGREES` | `'hello'` (str) | `'hello'` (str, jsonb string) |  |
| 2 | `upper` | `upper($.s)` | **PASS** `COMPILED_AGREES` | `'ABC'` (str) | `'ABC'` (str, jsonb string) |  |
| 3 | `lower_missing_null` | `lower($.s)` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 4 | `contains_substring_true` | `contains($.s, "ell")` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 5 | `contains_substring_false` | `contains($.s, "xyz")` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 6 | `contains_list_member_true` | `contains($.tags, "a")` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 7 | `contains_list_member_false` | `contains($.tags, "z")` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 8 | `contains_missing_haystack_false` | `contains($.s, "a")` | **PASS** `COMPILED_AGREES` | `False` (bool) | `False` (bool, jsonb boolean) |  |
| 9 | `concat_literals` | `concat("a", "b", "c")` | **PASS** `COMPILED_AGREES` | `'abc'` (str) | `'abc'` (str, jsonb string) |  |
| 10 | `concat_fields` | `concat($.first, " ", $.last)` | **PASS** `COMPILED_AGREES` | `'Jane Doe'` (str) | `'Jane Doe'` (str, jsonb string) |  |
| 11 | `concat_with_string_of_number` | `concat("n=", string($.n))` | **PASS** `COMPILED_AGREES` | `'n=5'` (str) | `'n=5'` (str, jsonb string) |  |

### `coercion` — 10 cases (PASS 10)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `number_of_string` | `number("3.5")` | **PASS** `COMPILED_AGREES` | `3.5` (float) | `3.5` (float, jsonb number) |  |
| 2 | `number_of_nonnumeric_null` | `number("abc")` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 3 | `number_of_bool` | `number(true)` | **PASS** `COMPILED_AGREES` | `1.0` (float) | `1` (int, jsonb number) |  |
| 4 | `string_of_int` | `string(5)` | **PASS** `COMPILED_AGREES` | `'5'` (str) | `'5'` (str, jsonb string) |  |
| 5 | `string_of_float` | `string(3.5)` | **PASS** `COMPILED_AGREES` | `'3.5'` (str) | `'3.5'` (str, jsonb string) |  |
| 6 | `string_of_bool` | `string(true)` | **PASS** `COMPILED_AGREES` | `'true'` (str) | `'true'` (str, jsonb string) |  |
| 7 | `string_of_null` | `string(null)` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 8 | `length_string` | `length($.s)` | **PASS** `COMPILED_AGREES` | `5` (int) | `5` (int, jsonb number) |  |
| 9 | `length_list` | `length($.list)` | **PASS** `COMPILED_AGREES` | `3` (int) | `3` (int, jsonb number) |  |
| 10 | `length_number_null` | `length($.n)` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |

### `numeric_funcs` — 11 cases (PASS 11)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `abs_literal` | `abs(-4)` | **PASS** `COMPILED_AGREES` | `4.0` (float) | `4` (int, jsonb number) |  |
| 2 | `abs_field` | `abs($.n)` | **PASS** `COMPILED_AGREES` | `2.5` (float) | `2.5` (float, jsonb number) |  |
| 3 | `floor_pos` | `floor(3.7)` | **PASS** `COMPILED_AGREES` | `3.0` (float) | `3` (int, jsonb number) |  |
| 4 | `ceil_pos` | `ceil(3.2)` | **PASS** `COMPILED_AGREES` | `4.0` (float) | `4` (int, jsonb number) |  |
| 5 | `floor_neg` | `floor(-3.2)` | **PASS** `COMPILED_AGREES` | `-4.0` (float) | `-4` (int, jsonb number) |  |
| 6 | `ceil_neg` | `ceil(-3.2)` | **PASS** `COMPILED_AGREES` | `-3.0` (float) | `-3` (int, jsonb number) |  |
| 7 | `round_half_up` | `round(2.5)` | **PASS** `COMPILED_AGREES` | `3.0` (float) | `3` (int, jsonb number) |  |
| 8 | `round_half_away_from_zero_neg` | `round(-2.5)` | **PASS** `COMPILED_AGREES` | `-3.0` (float) | `-3` (int, jsonb number) |  |
| 9 | `round_down` | `round(2.4)` | **PASS** `COMPILED_AGREES` | `2.0` (float) | `2` (int, jsonb number) |  |
| 10 | `round_ndigits` | `round(3.14159, 2)` | **PASS** `COMPILED_AGREES` | `3.14` (float) | `3.14` (float, jsonb number) |  |
| 11 | `round_ndigits_one` | `round(12.345, 1)` | **PASS** `COMPILED_AGREES` | `12.3` (float) | `12.3` (float, jsonb number) |  |

### `aggregates` — 11 cases (PASS 11)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `count_list` | `count($.list)` | **PASS** `COMPILED_AGREES` | `3.0` (float) | `3` (int, jsonb number) |  |
| 2 | `count_skips_null` | `count($.list)` | **PASS** `COMPILED_AGREES` | `2.0` (float) | `2` (int, jsonb number) |  |
| 3 | `sum_list` | `sum($.list)` | **PASS** `COMPILED_AGREES` | `6.0` (float) | `6` (int, jsonb number) |  |
| 4 | `sum_skips_nonnumeric` | `sum($.list)` | **PASS** `COMPILED_AGREES` | `4.0` (float) | `4` (int, jsonb number) |  |
| 5 | `avg_list` | `avg($.list)` | **PASS** `COMPILED_AGREES` | `4.0` (float) | `4` (int, jsonb number) |  |
| 6 | `min_list` | `min($.list)` | **PASS** `COMPILED_AGREES` | `2.0` (float) | `2` (int, jsonb number) |  |
| 7 | `max_list` | `max($.list)` | **PASS** `COMPILED_AGREES` | `8.0` (float) | `8` (int, jsonb number) |  |
| 8 | `max_varargs` | `max(1, 5, 3)` | **PASS** `COMPILED_AGREES` | `5.0` (float) | `5` (int, jsonb number) |  |
| 9 | `sum_varargs` | `sum(1, 2, 3)` | **PASS** `COMPILED_AGREES` | `6.0` (float) | `6` (int, jsonb number) |  |
| 10 | `avg_empty_null` | `avg($.list)` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 11 | `sum_missing_null` | `sum($.empty)` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |

### `conditional` — 3 cases (PASS 3)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `if_true_branch` | `if($.n > 0, "pos", "neg")` | **PASS** `COMPILED_AGREES` | `'pos'` (str) | `'pos'` (str, jsonb string) |  |
| 2 | `if_false_branch` | `if($.n > 0, "pos", "neg")` | **PASS** `COMPILED_AGREES` | `'neg'` (str) | `'neg'` (str, jsonb string) |  |
| 3 | `if_missing_is_false` | `if($.x, 1, 2)` | **PASS** `COMPILED_AGREES` | `2.0` (float) | `2` (int, jsonb number) |  |

### `composite` — 4 cases (PASS 4)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `near_due_predicate` | `days_between(today(), $.due_date) < 7` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 2 | `result_in_set` | `$.result == "FAIL" or $.result == "ERRO…` | **PASS** `COMPILED_AGREES` | `True` (bool) | `True` (bool, jsonb boolean) |  |
| 3 | `overdue_label` | `if(days_between(today(), $.due) < 0, "o…` | **PASS** `COMPILED_AGREES` | `'overdue'` (str) | `'overdue'` (str, jsonb string) |  |
| 4 | `days_left_derived` | `days_between(today(), $.due)` | **PASS** `COMPILED_AGREES` | `7.0` (float) | `7` (int, jsonb number) |  |

### `modulo_fmod` — 3 cases (PASS 3)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `mod_float_fmod` | `10.5 % 3` | **PASS** `COMPILED_AGREES` | `1.5` (float) | `1.5` (float, jsonb number) |  |
| 2 | `mod_float_ieee` | `0.5 % 0.1` | **PASS** `COMPILED_AGREES` | `0.09999999999999998` (float) | `0.09999999999999998` (float, jsonb number) |  |
| 3 | `mod_large_over_small_positive` | `$.a % $.b` | **PASS** `COMPILED_AGREES` | `1.4580013704758805` (float) | `1.4580013704758805` (float, jsonb number) |  |

### `string_ecma` — 4 cases (PASS 4)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `string_small_decimal_not_exp` | `string($.n)` | **PASS** `COMPILED_AGREES` | `'0.00001'` (str) | `'0.00001'` (str, jsonb string) |  |
| 2 | `string_tiny_exp` | `string($.n)` | **PASS** `COMPILED_AGREES` | `'1e-7'` (str) | `'1e-7'` (str, jsonb string) |  |
| 3 | `string_large_int_float` | `string($.n)` | **PASS** `COMPILED_AGREES` | `'1000000'` (str) | `'1000000'` (str, jsonb string) |  |
| 4 | `string_neg_small` | `string($.n)` | **PASS** `COMPILED_AGREES` | `'-0.00001'` (str) | `'-0.00001'` (str, jsonb string) |  |

### `date_total` — 2 cases (PASS 2)

| # | case | expr | outcome | Python | SQL | cause / reason |
| ---: | --- | --- | --- | --- | --- | --- |
| 1 | `date_add_out_of_range_null` | `date_add("9999-12-31", 100000)` | **PASS** `COMPILED_AGREES` | `None` (NoneType) | `SQL NULL` |  |
| 2 | `date_add_year_padded` | `date_add("0002-01-01", -1)` | **PASS** `COMPILED_AGREES` | `'0001-12-31'` (str) | `'0001-12-31'` (str, jsonb string) |  |

## `compile.py` KNOWN_DIVERGENCES (carried through so the finding cannot be lost)

| id | construct | expr | SQL | guarded | in fixture |
| --- | --- | --- | --- | --- | --- |
| `float8_overflow_raises` | + - * /  on float8 | Python returns +-inf (expr.py:614-621 has no overflow guard) | Postgres RAISES 'value out of range: overflow' (verified: select 1e30… | **NO** | no |
| `num_out_of_float8_range` | xpr.num / xpr.f8 on a JSON number or numeric … | Python float('1e999') == inf, _to_num returns inf | guarded to NULL (a bare cast would RAISE: select '1e999'::float8 -> o… | yes | no |
| `numeric_literal_inf` | a numeric literal that overflows, e.g. 1e400 | parse() builds ('num', inf) (expr.py:193, float() on the token) | compiler raises Uncompilable; jsonb cannot hold inf (to_jsonb('Infini… | yes | no |
| `jsonb_numeric_is_not_ieee_double` | == / != / < <= > >= over JSON numbers with >1… | Python parses JSON numbers to IEEE doubles first, so 1.00000000000000… | jsonb stores `numeric`; the two are DISTINCT. Ordering is routed thro… | **NO** | no |
| `unicode_case_and_collation` | lower() / upper() / string ordering on non-AS… | Python str.lower()/upper() and codepoint ordering | Postgres lower()/upper() follow the database collation; ordering is p… | **NO** | no |
| `extra_float_digits_guc` | string() / concat() of a number (xpr.ecma_num) | _num_to_str uses repr() == shortest round-trip (expr.py:334) | xpr.ecma_num reads float8's text output, which is the shortest round-… | **NO** | **yes** |
| `wall_clock_granularity` | today() / now() with no context clock | datetime.now(utc) evaluated once per evaluate() call, i.e. once per r… | xpr.now_ms falls back to now() == transaction timestamp, i.e. once pe… | **NO** | no |

These are divergences identified by the compiler's author and deliberately NOT fixed (FRAMING.md §3). They are reproduced verbatim in `results.json` under `known_divergences_from_compile_py`.
